apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::483532644071:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-K1K0TQ5QTZ5U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::483532644071:role/UdacityFlaskDeployKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T17:17:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1838"
  uid: 1c523d55-7456-45db-967c-9345eabac6d4
